{
  configRoot,
  moduleConfig,
  moduleTreeConfig,
  moduleTreeName,
  lib,
  pkgs,
  pkgs-unstable,
  ...
} @ args:

let
  # Get module configuration
  cfg = moduleConfig;

  pkgs_ = pkgs;


  # Registered by whichever backend module is enabled, `[]` if none is
  backends = moduleTreeConfig.networking.backend.enabled;

  usingNetworkd        =  lib.elem "networkd" backends;
  usingNetworkManager  =  lib.elem "networkmanager" backends;
in
{
  # === Options ===
  options = {
    "enable" = lib.mkOption {
      description = ''
        Whether to configure every wired interface for link-local.

        Together with `avahi.enable` that makes a cable between two hosts
        enough to reach either end by `<hostname>.local`, with nothing
        configured by hand and no interface named at either end.
      '';
      default = false;
      type = lib.types.bool;
    };

    "avahi"."enable" = lib.mkOption {
      description = ''
        Resolve and publish `.local` names over mDNS.

        A link-local address is picked at random from `169.254.0.0/16` and
        changes between boots.
      '';
      default = true;
      type = lib.types.bool;
    };

    "avahi"."denyInterfaces" = lib.mkOption {
      description = ''
        Interfaces `avahi` ignores entirely: it neither publishes on them
        nor answers a query arriving over one.

        mDNS announces this host's name and addresses to everything on the
        same segment. That is worth having on a link under your control and
        unwanted on an public access point.
        Denying the wireless interface keeps `.local` working over a direct
        cable and over a wired LAN, and stops the host announcing itself
        over Wi-Fi.

        Interface names only. Empty denies nothing, and lets
        mDNS run on every interface.
      '';
      default = [ "wlan0" "wlp2s0" ];
      type = lib.types.listOf lib.types.str;
    };
  };
  # === Options ===


  # === Config ===
  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = backends != [];
        message = ''
          `directLink` configures the enabled networking backend, and no
          backend is enabled.

          Enable one under `${moduleTreeName}.networking.backend`.
        '';
      }
    ];



    /*
      networkd applies the first `.network` file that matches and ignores the
      rest, so this has to carry everything the unit it displaces sets. `90-`
      sorts after a host's own units and before `99-ethernet-default-dhcp`.
    */
    systemd.network.networks = lib.mkIf usingNetworkd {
      "90-direct-link" = {
        matchConfig = {
          Type = "ether";

          # Physical interfaces only
          Kind = "!*";
        };

        networkConfig = {
          DHCP = "yes";
          LinkLocalAddressing = "yes";
          IPv6PrivacyExtensions = "kernel";
        };
      };
    };


    /*
      NetworkManager cannot match a device type from a profile, so the
      equivalent is a connection defaults section: 
      it fills in properties a profile leaves unset, autogenerated wired 
      profiles included. A profile that sets one explicitly keeps its own 
      value, and has to be recreated to pick these up.
    */
    networking.networkmanager.settings = lib.mkIf usingNetworkManager {
      "connection-direct-link" = {
        "match-device" = "type:ethernet";

        "ipv4.method" = "auto";
        "ipv4.link-local" = 4;  # "fallback"

        "ipv6.method" = "auto";
        # No `ipv6.link-local` exists since it's mandatory anyway
      };
    };



    services.avahi = lib.mkIf cfg.avahi.enable {
      enable = true;
      package = pkgs_.avahi;

      # Resolve `.local` through NSS
      nssmdns4 = true;
      nssmdns6 = true;

      # UDP 5353
      openFirewall = true;

      # `mkIf` so an empty list leaves the line out of the config
      denyInterfaces =
        lib.mkIf (cfg.avahi.denyInterfaces != []) cfg.avahi.denyInterfaces;

      # Answers for this host as `<hostname>.local`
      publish = {
        enable = true;
        addresses = true;
      };
    };
  };
  # === Config ===
}
